{"name": "Запрос с несуществующим заказом возвращает ошибку", "status": "passed", "description": "Запрос получения заказа с несуществующим трэк номером заказа возвращает код ответа 404 Not Found и \"message\":  Заказ не найден", "steps": [{"name": "Отправляем запрос c несуществующим номером заказом", "status": "passed", "steps": [{"name": "Получаем объект с заказом", "status": "passed", "parameters": [{"name": "track_number", "value": "'9999999'"}], "start": 1758134662509, "stop": 1758134663495}], "start": 1758134662509, "stop": 1758134663495}], "start": 1758134662509, "stop": 1758134663498, "uuid": "343547c7-0a6d-4fd9-b46b-9ea246967e56", "historyId": "7779ce123e6a6b7e148450a932028192", "testCaseId": "7779ce123e6a6b7e148450a932028192", "fullName": "tests.test_get_orders.TestGetOrderByNumber#test_error_get_order_with_nonexistent_number", "labels": [{"name": "subSuite", "value": "class TestGetOrderByNumber: Получить заказ по его трек номеру"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "host", "value": "MacBook-Pro-Ivan.local"}, {"name": "thread", "value": "8419-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}], "titlePath": ["tests", "test_get_orders.py", "TestGetOrderByNumber"]}